# Generated by Django 3.0.8 on 2020-08-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200805_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='image_url',
            field=models.URLField(default='https://www.britannica.com/story/why-do-cats-sleep-so-much'),
        ),
    ]
